### PR TITLE
fix for latest php7 head

### PR DESCRIPTION
**Pull request by hjanuschka**
hello

following changes enable compile against the current php7 master
there is no if-def-dance - so it does not compile on php5.6 5.5 - but should be a quick one - or maybe keep it in a seperate branch?

make test passes all tests - maybe this is a inspiration for someone who is doing the php-lua builds!

note includes @ktemkin 's config.m4 patch for debian/ubuntu

### CODE REVIEW

**Comment by hjanuschka** [comment]
wow - fast - you sure it should be in the master branch? because it breaks building against any php version prior to php7-head?

could you add me to the LUA_AUTHORS (i forgot)

**Comment by laruence** [comment]
I will make a new release before PHP7 comes out.

sure, maybe you could send another PR? I will merge it(author)

**Comment by laruence** [comment]
maybe checkout a new branch for 5.x , of course before this commit

**Comment by hjanuschka** [comment]
ok i have no clue how to re-open that pull request did a new one #14 for the authors stuff.

right now i don't have the need for php5.x - but i try to get a devbox up and running and try to do the backport.

regards

**Pull request merged**
